name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite
  workflow_dispatch: # Permite rodar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Clona o repositório
      - name: Clonar o repositório
        uses: actions/checkout@v2

      # Configura a cobrinha e gera o SVG
      - name: Gerar Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: Henrique-Ambiel
          outputs: dist/snake.svg

      # Atualiza o arquivo no README
      - name: Commit e Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Atualizando animação da cobrinha"
          git push
